export const FETCH_REQUEST_START = 'FETCH_REQUEST_START'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE'

export const FETCH_REPO_LIST_BEGIN = 'FETCH_REPO_LIST_BEGIN'
export const FETCH_REPO_LIST_SUCCESS = 'FETCH_REPO_LIST_SUCCESS'
export const FETCH_REPO_LIST_FAILURE = 'FETCH_REPO_LIST_FAILURE'
