export const FETCH_REPO_LIST_BEGIN = 'FETCH_REPO_LIST_BEGIN'
export const FETCH_REPO_LIST_SUCCESS = 'FETCH_REPO_LIST_SUCCESS'
export const FETCH_REPO_LIST_FAILURE = 'FETCH_REPO_LIST_FAILURE'
export const FETCH_REPO_BEGIN = 'FETCH_REPO_BEGIN'
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'
export const FETCH_REPO_FAILURE = 'FETCH_REPO_FAILURE'
export const NAVLINK_CLICK_REPO = 'NAVLINK_CLICK_REPO'
export const REPO_PATH_PREFIX = 'repos'

export const LIST_COMPONENT_CLASS_NAME = 'ns-list'
export const LIST_ITEM_COMPONENT_CLASS_NAME = 'ns-list-item'
export const REPO_COMPONENT_CLASS_NAME = 'ns-repo'
export const BADGE_COMPONENT_CLASS_NAME = 'ns-badge'
export const GROUP_SPACER_COMPONENT_CLASS_NAME = 'ns-group-spacer'
export const DETAIL_TABLE_COMPONENT_CLASS_NAME = 'ns-detail-table'
export const DETAIL_TABLE_ENTRY_COMPONENT_CLASS_NAME = 'ns-detail-table-entry'
export const PAGE_LIST_COMPONENT_CLASS_NAME = 'ns-page-list'
export const NAVBAR_COMPONENT_CLASS_NAME = 'ns-nav-bar'
