# merge fixer
service: projects-nikitas-link # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'us-east-1'}
custom:
  account: ${opt:account}
  cloudfront-app:
    region: us-east-1
    bucketName: ${opt:bucket}
    useragentsecret: ${opt:uasecret}
    acm-region: us-east-1
    certid: ${opt:certid}
    logbucket: "${opt:logbucket}.s3.amazonaws.com"
    logbucket-prefix: "${self:provider.stage}-${self:service}"
    alias: ${opt:bucket}
    hostedzonename: ${opt:hzname}
  report-bucket: "${opt:bucket}-REPORTS"
resources:
  Resources:
    WebRedirectS3Bucket: ${file(cloudfront-app.yml):WebRedirectS3Bucket}
    RedirectCloudFrontDistribution: ${file(cloudfront-app.yml):RedirectCloudFrontDistribution}
    WWWWebAppRecord: ${file(cloudfront-app.yml):WWWWebAppRecord}
    WebAppRecord: ${file(cloudfront-app.yml):WebAppRecord}
    WebAppS3Bucket: ${file(cloudfront-app.yml):WebAppS3Bucket}
    WebAppS3BucketPolicy: ${file(cloudfront-app.yml):WebAppS3BucketPolicy}
    WebAppDistribution: ${file(cloudfront-app.yml):WebAppDistribution}
    ReportS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.report-bucket}
    ReportS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: ReportS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.report-bucket}/*
              Condition:
                StringLike:
                  ## only allow get requests to this bucket if they include a
                  ## secret user agent string... this is an easy way to only allow
                  ## access from a designated cloudfront distribution, but a poor
                  ## security solution, because it relies on security by obfuscration
                  aws:UserAgent: ${self:custom.cloudfront-app.useragentsecret}
